# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 264)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/resource/moncenter_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_vim = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_vim.sizePolicy().hasHeightForWidth())
        self.pushButton_vim.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resource/resource/esp32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_vim.setIcon(icon1)
        self.pushButton_vim.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_vim.setObjectName("pushButton_vim")
        self.verticalLayout.addWidget(self.pushButton_vim)
        self.pushButton_post_processing = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_post_processing.sizePolicy().hasHeightForWidth())
        self.pushButton_post_processing.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resource/resource/post_processing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_post_processing.setIcon(icon2)
        self.pushButton_post_processing.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_post_processing.setObjectName("pushButton_post_processing")
        self.verticalLayout.addWidget(self.pushButton_post_processing)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное меню ВИМ"))
        self.pushButton_vim.setText(_translate("MainWindow", "Перейти в ВИМ менеджер"))
        self.pushButton_post_processing.setText(_translate("MainWindow", "Перейти в пост обработку ВИМ"))
import resource_rc
